-- INSERSIONES --
USE historiaInteractiva;

-- Insertar datos en la tabla usuario
INSERT INTO usuario (nombre, apellido, correo_electronico, contrasena, estado, codigo) VALUES
('Juan', 'Pérez', 'juan.perez@example.com', SHA2('password1', 256), 1, 'codigo1'),
('María', 'Gómez', 'maria.gomez@example.com', SHA2('password2', 256), 1, 'codigo2'),
('Carlos', 'López', 'carlos.lopez@example.com', SHA2('password3', 256), 1, 'codigo3'),
('Ana', 'Martínez', 'ana.martinez@example.com', SHA2('password4', 256), 1, 'codigo4'),
('Luis', 'García', 'luis.garcia@example.com', SHA2('password5', 256), 1, 'codigo5'),
('Elena', 'Rodríguez', 'elena.rodriguez@example.com', SHA2('password6', 256), 1, 'codigo6'),
('Pedro', 'Fernández', 'pedro.fernandez@example.com', SHA2('password7', 256), 1, 'codigo7'),
('Sofía', 'Torres', 'sofia.torres@example.com', SHA2('password8', 256), 1, 'codigo8'),
('Jorge', 'Sánchez', 'jorge.sanchez@example.com', SHA2('password9', 256), 1, 'codigo9'),
('Marta', 'Ramírez', 'marta.ramirez@example.com', SHA2('password10', 256), 1, 'codigo10'),
('Alberto', 'Flores', 'alberto.flores@example.com', SHA2('password11', 256), 1, 'codigo11'),
('Lucía', 'Hernández', 'lucia.hernandez@example.com', SHA2('password12', 256), 1, 'codigo12'),
('David', 'Jiménez', 'david.jimenez@example.com', SHA2('password13', 256), 1, 'codigo13'),
('Paula', 'Díaz', 'paula.diaz@example.com', SHA2('password14', 256), 1, 'codigo14'),
('Manuel', 'Vargas', 'manuel.vargas@example.com', SHA2('password15', 256), 1, 'codigo15');

-- Insertar datos en la tabla historia
INSERT INTO historia (titulo, autor_id) VALUES
('Historia de Aventura', 1),
('Historia de Ciencia Ficción', 2),
('Historia de Misterio', 3),
('Historia de Fantasía', 4),
('Historia de Romance', 5),
('Historia de Terror', 6),
('Historia de Suspenso', 7),
('Historia de Comedia', 8),
('Historia de Drama', 9),
('Historia de Acción', 10),
('Historia de Histórica', 11),
('Historia de Western', 12),
('Historia de Bélica', 13),
('Historia de Musical', 14),
('Historia de Animación', 15);
-- ESCCENA
INSERT INTO escena (historia_id, titulo, video, descripcion) VALUES
(1, 'Escena 1', 'video1.mp4', 'Descripción de la escena 1'),
(1, 'Escena 2', 'video2.mp4', 'Descripción de la escena 2'),
(2, 'Escena 1', 'video3.mp4', 'Descripción de la escena 1'),
(2, 'Escena 2', 'video4.mp4', 'Descripción de la escena 2'),
(3, 'Escena 1', 'video5.mp4', 'Descripción de la escena 1'),
(3, 'Escena 2', 'video6.mp4', 'Descripción de la escena 2'),
(4, 'Escena 1', 'video7.mp4', 'Descripción de la escena 1'),
(4, 'Escena 2', 'video8.mp4', 'Descripción de la escena 2'),
(5, 'Escena 1', 'video9.mp4', 'Descripción de la escena 1'),
(5, 'Escena 2', 'video10.mp4', 'Descripción de la escena 2'),
(6, 'Escena 1', 'video11.mp4', 'Descripción de la escena 1'),
(6, 'Escena 2', 'video12.mp4', 'Descripción de la escena 2'),
(7, 'Escena 1', 'video13.mp4', 'Descripción de la escena 1'),
(7, 'Escena 2', 'video14.mp4', 'Descripción de la escena 2'),
(8, 'Escena 1', 'video15.mp4', 'Descripción de la escena 1'),
(8, 'Escena 2', 'video16.mp4', 'Descripción de la escena 2'),
(9, 'Escena 1', 'video17.mp4', 'Descripción de la escena 1'),
(9, 'Escena 2', 'video18.mp4', 'Descripción de la escena 2'),
(10, 'Escena 1', 'video19.mp4', 'Descripción de la escena 1'),
(10, 'Escena 2', 'video20.mp4', 'Descripción de la escena 2'),
(11, 'Escena 1', 'video21.mp4', 'Descripción de la escena 1'),
(11, 'Escena 2', 'video22.mp4', 'Descripción de la escena 2'),
(12, 'Escena 1', 'video23.mp4', 'Descripción de la escena 1'),
(12, 'Escena 2', 'video24.mp4', 'Descripción de la escena 2'),
(13, 'Escena 1', 'video25.mp4', 'Descripción de la escena 1'),
(13, 'Escena 2', 'video26.mp4', 'Descripción de la escena 2'),
(14, 'Escena 1', 'video27.mp4', 'Descripción de la escena 1'),
(14, 'Escena 2', 'video28.mp4', 'Descripción de la escena 2'),
(15, 'Escena 1', 'video29.mp4', 'Descripción de la escena 1'),
(15, 'Escena 2', 'video30.mp4', 'Descripción de la escena 2');
-- Insertar datos en la tabla decision
INSERT INTO decision (escena_id, descripcion, escena_destino_id) VALUES
(1, 'Decisión 1', 2),
(1, 'Decisión 2', 3),
(2, 'Decisión 1', 4),
(2, 'Decisión 2', 5),
(3, 'Decisión 1', 6),
(3, 'Decisión 2', 7),
(4, 'Decisión 1', 8),
(4, 'Decisión 2', 9),
(5, 'Decisión 1', 10),  
(5, 'Decisión 2', 11),
(6, 'Decisión 1', 12),
(6, 'Decisión 2', 13),
(7, 'Decisión 1', 14),
(7, 'Decisión 2', 15),
(8, 'Decisión 1', 16),
(8, 'Decisión 2', 17),
(9, 'Decisión 1', 18),
(9, 'Decisión 2', 19),
(10, 'Decisión 1', 20),
(10, 'Decisión 2', 21),
(11, 'Decisión 1', 22),
(11, 'Decisión 2', 23),
(12, 'Decisión 1', 24),
(12, 'Decisión 2', 25),
(13, 'Decisión 1', 26),
(13, 'Decisión 2', 27),
(14, 'Decisión 1', 28),
(14, 'Decisión 2', 29),
(15, 'Decisión 1', 30);
-- Insertar datos en la tabla estado_publicacion
INSERT INTO estado_publicacion (historia_id, estado) VALUES
(1, 'Borrador'),
(2, 'Publicado'),
(3, 'En revisión'),
(4, 'Borrador'),
(5, 'Publicado'),
(6, 'En revisión'),
(7, 'Borrador'),
(8, 'Publicado'),
(9, 'En revisión'),
(10, 'Borrador'),
(11, 'Publicado'),
(12, 'En revisión'),
(13, 'Borrador'),
(14, 'Publicado'),
(15, 'En revisión');
